---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: k8s-monitor-dns
  namespace: "kube-system"
  labels:
    app: k8s-monitor-dns
rules:
  - apiGroups:
    - ''
    resources:
    - ''
    - endpoints
    verbs:
    - get
    - list
    - watch

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: k8s-monitor-dns
  labels:
    app: k8s-monitor-dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-monitor-dns
subjects:
  - name: k8s-monitor-dns
    namespace: "kube-system"
    kind: ServiceAccount
